image: node:6.11
pipelines:
  default:
    - step:
        caches:
          - node
        script:
          - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - &&\
          - sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list' &&\
          - apt-get update &&\
          - apt-get install -y google-chrome-stable
          - npm install
          - npm test
